"""Token selection and autoregressive decoding policies.

A trained model doesn't output "the next token" — it outputs a probability
for EVERY possible next token (via softmax over its logits). Turning that
whole distribution into one chosen token is a separate decision with real
consequences for output quality, and this file collects the standard
strategies for making it: greedy (always the single most likely token),
temperature (reshaping how "peaked" the distribution is before sampling),
and top-k (restricting sampling to only the k most likely candidates).
None of these change what the MODEL knows — they change how much of that
knowledge's uncertainty is allowed to show up as variety in the output.
"""

from __future__ import annotations

import torch
from torch import nn
from torch.nn import functional as F


def sample_next_token(
    logits: torch.Tensor,
    temperature: float = 1.0,
    top_k: int | None = None,
    greedy: bool = False,
) -> torch.Tensor:
    """Choose one token from a batch of next-token logits.

    The three parameters below trade off diversity against coherence, and
    are usually tuned by ear rather than derived formally:

    GREEDY (deterministic): always pick the single highest-scoring token.
    Gives the most locally "confident" output but tends to get stuck in
    repetitive loops for anything beyond a sentence or two — see this
    project's --greedy generation samples, which visibly degenerate into
    repeating the same phrase, because once a model talks itself into a
    locally-safe cycle there's no randomness available to break out of it.

    TEMPERATURE (reshapes confidence before sampling): dividing logits by
    a value below 1.0 makes the distribution MORE peaked (more confident,
    closer to greedy); above 1.0 makes it FLATTER (more uniform, more
    random/creative, but more likely to pick a poor token). Temperature
    exactly 1.0 samples from the model's own, unmodified probability
    estimate.

    TOP-K (restricts the candidate pool before sampling): keep only the k
    highest-scoring tokens and sample among just those (renormalized),
    discarding the long tail of unlikely-but-nonzero-probability tokens
    entirely. Without this, temperature sampling alone can occasionally
    pick a token from that long tail — individually unlikely, but with
    enough tail mass in aggregate that it happens often enough to
    noticeably hurt output quality (a very small chance repeated over many
    generation steps). Restricting to the top-k candidates trades away
    that rare tail risk for a bit less diversity.
    """

    if logits.ndim != 2:
        raise ValueError(
            "logits must have shape (batch, vocabulary)"
        )

    if temperature <= 0.0:
        raise ValueError("temperature must be positive")

    vocabulary_size = logits.shape[-1]

    if top_k is not None and not (
        1 <= top_k <= vocabulary_size
    ):
        raise ValueError(
            "top_k must be between 1 and the vocabulary size"
        )

    if greedy:
        return torch.argmax(
            logits,
            dim=-1,
            keepdim=True,
        )

    scaled_logits = logits / temperature

    if top_k is not None:
        top_values, top_indices = torch.topk(
            scaled_logits,
            k=top_k,
            dim=-1,
        )

        # Build a fresh tensor that's -inf everywhere except at the top-k
        # positions (which keep their scaled scores). softmax(-inf) == 0,
        # so this is what actually enforces "only these k tokens are
        # eligible" — anything outside the top-k gets exactly zero
        # probability after the softmax below, not just a small one.
        filtered_logits = torch.full_like(
            scaled_logits,
            float("-inf"),
        )

        scaled_logits = filtered_logits.scatter(
            dim=-1,
            index=top_indices,
            src=top_values,
        )

    probabilities = F.softmax(
        scaled_logits,
        dim=-1,
    )

    # torch.multinomial draws one random sample per row, weighted by that
    # row's probabilities — this is the actual "randomness" in text
    # generation; everything above just shapes the distribution being
    # sampled from.
    return torch.multinomial(
        probabilities,
        num_samples=1,
    )


@torch.no_grad()
def generate_tokens(
    model: nn.Module,
    starting_tokens: torch.Tensor,
    max_new_tokens: int,
    block_size: int,
    temperature: float = 1.0,
    top_k: int | None = None,
    greedy: bool = False,
) -> torch.Tensor:
    """Autoregressively extend a batch of starting tokens.

    "Autoregressive" means each new token is generated by feeding the
    ENTIRE sequence so far (prompt + everything generated up to this
    point) back through the model and reading off its prediction for the
    next position — there is no separate "memory" carried between steps;
    the growing token sequence itself IS the model's only state. This is
    why generation cost grows with output length: predicting the 500th
    token requires a full forward pass over (up to) 500 tokens of context,
    not a cheap incremental update.

    @torch.no_grad() disables PyTorch's gradient tracking for this entire
    function — generation never needs to compute gradients (there's no
    loss being minimized here, just a forward pass), so tracking them
    would only waste memory and time.
    """

    if max_new_tokens < 0:
        raise ValueError("max_new_tokens cannot be negative")

    if block_size < 1:
        raise ValueError("block_size must be positive")

    if (
        starting_tokens.ndim != 2
        or starting_tokens.shape[1] < 1
    ):
        raise ValueError(
            "starting_tokens must contain at least one token"
        )

    tokens = starting_tokens

    for _ in range(max_new_tokens):
        # Every Transformer here has a fixed maximum context length
        # (block_size) — once the sequence grows longer than that, only
        # the most recent block_size tokens are fed in. This means very
        # early context (e.g. the start of a long prompt) is gradually
        # "forgotten" once generation runs long enough, a genuine
        # limitation of this fixed-context-window architecture family
        # (as opposed to, e.g., recurrent models, which carry forward a
        # compressed summary of arbitrarily long history instead).
        visible_tokens = tokens[:, -block_size:]

        logits, _ = model(visible_tokens)

        # Only the LAST position's prediction is "what comes next" — every
        # earlier position's prediction in this same forward pass was
        # already used (in a training context) or is simply not needed
        # here.
        final_logits = logits[:, -1, :]

        next_token = sample_next_token(
            final_logits,
            temperature=temperature,
            top_k=top_k,
            greedy=greedy,
        )

        tokens = torch.cat(
            (tokens, next_token),
            dim=1,
        )

    return tokens
